---

- name: Clone latency_check repo
  git:
    repo: https://github.com/sovrn/latency_check.git
    dest: /opt/latency_check
    accept_hostkey: yes
  tags:
    - latency_check

- name: Copy latency_check configuration
  template:
    src: opt/latency_check/config.json.j2
    dest: "{{lc_install_dir}}/config.json"
  tags:
    - latency_check

- name: Install latency_check SystemD files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: etc/systemd/system/latency_check.service.j2, dest: /etc/systemd/system/latency_check.service }
    - { src: etc/systemd/system/latency_check.timer.j2, dest: /etc/systemd/system/latency_check.timer }
  when: ansible_service_mgr == 'systemd'
  tags:
    - latency_check

- name: Activate latency_check SystemD script
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - latency_check.service
    - latency_check.timer
  when: ansible_service_mgr == 'systemd'
  tags:
    - latency_check

- name: Install latency_check Cron job
  cron:
    job: /bin/bash -c "/usr/bin/time /usr/bin/python2 {{lc_install_dir}}/latency_check.py |& /usr/bin/logger"
    name: latency_check
    minute: "*/5"
  when: ansible_service_mgr != 'systemd'
  tags:
    - latency_check
