---

# You can pass '-e "servers=comma-separated-hostnames.example.com"' to the ansible-playbook command or replace hosts with your own list.
# There are also a few variables under `roles/latency_check/vars/main.yml`
- hosts: "{{ servers }}"
  roles:
    - latency_check
